# Generated by Django 4.2.3 on 2023-07-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CatBreed',
                'verbose_name_plural': 'CatBreeds',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('image', models.CharField(max_length=250)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.catbreed')),
            ],
        ),
    ]
