# Generated by Django 4.2.3 on 2023-07-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cat_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='catToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='toys',
            field=models.ManyToManyField(blank=True, related_name='catToys', to='main_app.cattoy'),
        ),
    ]
